### ISSUE TITLE
AttributeError: module 'deepcell.utils' has no attribute 'get_image'

### ISSUE THREAD

**Issue by ArtemSokolov** [vanvalenlab/deepcell-applications#12]
I am getting the following error when attempting to run the Docker container:
```
Traceback (most recent call last):
  File "main.py", line 156, in <module>
    compartment=ARGS.compartment
  File "main.py", line 77, in run
    nuclear_img = deepcell.utils.get_image(nuclear_path)
AttributeError: module 'deepcell.utils' has no attribute 'get_image'
```

Command executed:
```
docker run --rm -v "$PWD":/data vanvalenlab/deepcell-applications --nuclear-image /data/exemplar-001.ome.tif --output-directory /data
```

where `exemplar-001.ome.tif` is a stitched and registered image from MCMICRO's [minimal working dataset](https://mcmicro.org/datasets.html). Assuming [nextflow and Docker are installed](https://mcmicro.org/documentation/installation.html), the .ome.tif can be reproduced with:

```
nextflow run labsyspharm/mcmicro/exemplar.nf --name exemplar-001 --path .
nextflow run labsyspharm/mcmicro --in ./exemplar-001 --stop-at registration
ls ./exemplar-001/registration/exemplar-001.ome.tif
```

**Comment by willgraf** [comment]
Can you please confirm which version of `deepcell` you are using?

Also, the Docker image tag you are using (if using a pre-built image).

**Comment by ArtemSokolov** [comment]
Hi @willgraf,

The container image was built directly from the GitHub repo (commit 4f71fb2da1ccb64103cfc8f6e88d1ddba69eb183) by running

`docker build -t vanvalenlab/deepcell-applications .`

as suggested in the [README](https://github.com/vanvalenlab/deepcell-applications#build-the-image).

**Comment by willgraf** [comment]
Thank you! It looks like this is an issue with breaking changes between `deepcell` 0.6.x and 0.8.x.

A fix is in-progress, but  in the meantime, the `get_image` function can be imported from `deepcell.utils.io_utils` as a patch.
