### ISSUE TITLE
Problems reading OME-TIFF files with LZW compression

### ISSUE THREAD

**Issue by ArtemSokolov** [vanvalenlab/deepcell-applications#26]
Dear Mesmer developers,

Happy New Year! Hope you are all doing well.

Users report problems reading LZW-compressed OME-TIFF files: https://forum.image.sc/t/converting-scn-files-to-ome-tiff-for-use-in-mcmicro/61675

Possible solution(s):

* Increment Tensorflow version, such that the underlying Python version is >= 3.7
* `pip install imagecodecs`, which is used by `tifffile` to read LZW compression

-Artem

**Comment by ngreenwald** [comment]
@willgraf I'm assuming we're going to upgrade to python 3.7 eventually. Do you want me to add imagecodecs in the interim?

**Comment by willgraf** [comment]
The base TensorFlow image uses Python 3.6 so unfortunately we are pinned to that until they upgrade.

**Comment by willgraf** [comment]
Let's begin testing `imagecodecs` though it seems like an addition required in `deepcell` rather than in `deepcell-applications`.

**Comment by ngreenwald** [comment]
Hey @ArtemSokolov, 
Could you provide a code snippet to generate an LZW file that we can add to our test suite to make sure the update is working?

**Comment by ArtemSokolov** [comment]
Good point. We'll need it too, to test our modules.
Just requested it from the original user: https://forum.image.sc/t/converting-scn-files-to-ome-tiff-for-use-in-mcmicro/61675/8

Will keep you updated!

**Comment by ArtemSokolov** [comment]
Just wanted to follow up on this. Installing `imagecodecs` inside the container fixed the issue for us: https://github.com/HMS-IDAC/UnMicst/commit/5e22d87179701b8151664dd50bd5640d77a242d3

`tifffile` uses `imagecodecs` internally, so no further code modifications are needed if `tifffile` is used to load images.

**Comment by aandytu** [comment]
Is there a docker image available with `imagecodecs` already included? Trying to run mesmer as part of `mcmicro`, but it seems like this issue hasn't been fixed by the latest version of the image (0.4.0). A 0.4.1 version would be great.

**Comment by aandytu** [comment]
tested some changes here: https://github.com/vanvalenlab/deepcell-applications/pull/35
