### ISSUE TITLE
generated mask appears black in windows photo viewer

### ISSUE THREAD

**Issue by E5ten** [vanvalenlab/deepcell-applications#27]
When opening a mask.tif created with mesmer through this script in windows photo viewer, it looks like a completely black image, but a mask generated using the web interface at https://www.deepcell.org/predict appears normally. The problem is not that the mask is actually a black image, because I can see it by opening it in imageJ. Any idea what differences in the local and web interfaces could lead to this?

**Comment by msschwartz21** [comment]
My best guess is that in the web interface we cast the mask to float32 prior to saving, while in the application we leave the data type as is. While both the deepcell-applications and the web interface use the same models and prediction interface, the functions to save out the final results are different.

**Comment by E5ten** [comment]
Is the code the web interface uses to save the results available for me to look at? I didn't notice a repo for it in the organization but I could have easily missed it/thought a relevant repo was something else.

**Comment by msschwartz21** [comment]
The `kiosk-redis-consumer` repo handles model predictions for the web interface. I think the relevant function for saving data is here https://github.com/vanvalenlab/kiosk-redis-consumer/blob/2ab84a3029814b2afee5039d72e7658f2a5f9ac5/redis_consumer/utils.py#L111

**Comment by ngreenwald** [comment]
I agree, this is almost certainly a dtype issue. Large dtypes don't show up
well with default viewers, because the values are rendered as a proportion
of maximum intensity, which is quite small

**Comment by ngreenwald** [comment]
Nope, the segmentation output can easily be converted between dtypes. Some python functions for segmentation analysis expect labeled_images to be of type `int`, so you may run into errors if you're using packages like scikit-image, but the data is the same and can be converted back and forth
