### ISSUE TITLE
Memory usage with large .ome.tiff images

### ISSUE THREAD

**Issue by FloWuenne** [vanvalenlab/deepcell-applications#30]
Hi Mesmer developers,

we are routinely processing large .ome.tiff images, usually with dimensions around:
39000 x 39000 pixel with a pixel resolution of 0.233 um/pixel with file sizes between 40-100GB.

We have noticed that running these jobs requires a large amount of RAM to be available, otherwise they will fail. 
Is there a way to reduce memory consumption on large images? Will using a gpu node reduce this? 

Thank you for your help with this question!

**Comment by ngreenwald** [comment]
Hey Florian, 
The current Mesmer container reads in the entire image for processing. As a result, you will need enough RAM to store the image in memory. Using a GPU will make the processing faster, but I don't think it will change the underlying memory needs appreciably. 

One easy workaround would be to generate smaller crops, say for example 10k by 10k, and feed those to Mesmer. Given how large your images are, the stitching errors at the border between crops would unlikely to be a significant issue. 

If you have ideas for how to better deal with large images happy to discuss!

**Comment by FloWuenne** [comment]
Thanks for the details and explanations, Noah! 

So I just went through the code and correct me if I am wrong, but when you say load the entire image it does really mean the entire image with all channels right (using [get_image](https://github.com/vanvalenlab/deepcell-applications/blob/d3f1050e9c43562034279a504f22fe7a22f2bb28/deepcell_applications/io.py#L49)) ? 

One way to potentially reduce RAM usage could be to write a load_image_save_ram() function, that instead of loading the full image directly only loads the nuclear (and optionally) the membrane channel. that way, the entire image is never stored in RAM. Is there a particular reason for loading the entire image once? To be fair, the user might just extract the DAPI channel from his image beforehand and only feed this into Mesmer, but this might be often be impractical for users too...

**Comment by ngreenwald** [comment]
Right, so if you look at the rest of the `load_image` function, you'll see there's logic in there for selecting which channels to use for Mesmer. Some users have a simple 2-channel image, that is already formatted correctly. However, often there will be a large, multi-dimensional TIF, and the user wants some combination of channels to be used for the pan-membrane channel, for example CD45 and ECAD. 

We currently load the entire thing, then subset according to which channels the user provided, to be flexible about what formatting is required beforehand.

**Comment by FloWuenne** [comment]
Thanks for the clarification, Noah! 

I think we might build an option to save memory directly into MCMICRO before applying mesmer, to give people with lots large image area and many channels the option to reduce their memory usage drastically if they want.
