### ISSUE TITLE
A Docker image without ENTRYPOINT

### ISSUE THREAD

**Issue by ArtemSokolov** [vanvalenlab/deepcell-applications#32]
Would it be possible to drop `ENTRYPOINT` from the `Dockerfile`, or alternatively build a parallel image without it?

When wrapped by Nextflow, the container is executed as:
```
docker run -i --cpus 1.0 -v /workspace:/workspace -w "$PWD" --name $NXF_BOXID vanvalenlab/deepcell-applications:0.4.0 /bin/bash ...
```

which a) resets the work directory and b) runs the command through `/bin/bash`. The former results in:

```
python: can't open file 'run_app.py': [Errno 2] No such file or directory
```

because the `ENTRYPOINT` directive doesn't specify the full path and relies on `WORKDIR`, which gets overwritten at runtime. If the `ENTRYPOINT` is modified to specify the full path to `run_app.py`, the `/bin/bash` wrapper then creates the following problem:

```
  usage: run_app.py [-h] {mesmer} ...
  run_app.py: error: argument app: invalid choice: '/bin/bash' (choose from 'mesmer')
```

My understanding is that Nextflow is not unique in this, and other workflow languages would also have issues with the entrypoint.

**Comment by ngreenwald** [comment]
Hey @ArtemSokolov, I think the reason this was originally added was to support execution of the image as a standalone container, like we have [here](https://github.com/vanvalenlab/deepcell-applications#script-command) in the readme. If we remove the entrypoint line, is there a way we can keep it compatible with both workflow languages and user-execution?
If so, we would be happy to make the change.

**Comment by ArtemSokolov** [comment]
Hey @ngreenwald. Sorry for the slow response; we were battling with the recent changes in how Nextflow executes containers.

We were able to come up with a way to override custom entrypoints on the pipeline side: https://github.com/labsyspharm/mcmicro/pull/453/files

**Comment by ngreenwald** [comment]
No problem, glad you were able to work it out! Don't hesitate to reach out if any other issues come up, we've heard great things from the people using mcmicro to run Mesmer.
